# Generated by Django 3.1.4 on 2020-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='head',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
