# Generated by Django 3.1.4 on 2020-12-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_headofdept'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.headofdept'),
        ),
    ]
